import cron from "node-cron";
import { Resend } from "resend";
import { config } from "dotenv";
import path from "path";
import Order from "../models/Order.js";

// Read .env file
config({ path: path.resolve(process.cwd(), ".env") });

// Get Resend API Key from .env
const resend = new Resend(process.env.RESEND_API_KEY);

export const initSalesReportJob = () => {
    // Cron Expression to run every night at exactly 12:00 AM: '0 0 * * *'
    // If you want to send every 1 minute during the trial period, you can change it to '* * * * *'
    cron.schedule("* * * * *", async () => {
        console.log("Running Daily Sales Report Cron Job...");

        try {
            // 1. Setting the start (00:00:00) and end (23:59:59) of today's date
            const startOfDay = new Date();
            startOfDay.setHours(0, 0, 0, 0);

            const endOfDay = new Date();
            endOfDay.setHours(23, 59, 59, 999);

            // 2. Search the DB for all orders entered today
            const todaysOrders = await Order.find({
                createdAt: { $gte: startOfDay, $lte: endOfDay },
            });

            // 3. Calculating the total sales volume for today
            const totalSales = todaysOrders.reduce((sum, order) => sum + order.totalPrice, 0);
            const totalOrders = todaysOrders.length;

            // 4. Preparing HTML Email Template
            const emailHtml = `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
          <h2 style="color: #2c3e50;">📊 Daily Sales Report</h2>
          <p>Here is the automated sales summary for today (📅 ${new Date().toLocaleDateString()}):</p>
          <hr />
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Total Orders:</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${totalOrders} orders</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold; color: #27ae60;">Total Revenue:</td>
              <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold; color: #27ae60;">$${totalSales.toFixed(2)}</td>
            </tr>
          </table>
          <br />
          <p style="font-size: 12px; color: #7f8c8d;">This is an automated system email generated by adv-ecommerce-api.</p>
        </div>
      `;

            // 5. Sending email to Admin by using Resend Service
            // Accept API  Response data
            const { data, error } = await resend.emails.send({
                from: "onboarding@resend.dev",
                to: process.env.ADMIN_EMAIL,
                subject: `Daily Sales Report - ${new Date().toLocaleDateString()}`,
                html: emailHtml,
            });

            // Response has error
            if (error) {
                console.error("Resend API Error Response:", error);
                return;
            }

            console.log("Sales Report Email Sent Successfully.");
        } catch (error) {
            console.error("Error in Sales Report Cron Job:", error.message);
        }
    });
};